### ISSUE TITLE
Update layout to use flexbox

### ISSUE THREAD

**Issue by johnhaup** [aaranda82/US-Tool#13]
Let's update the layout to use `flexbox` instead of `vh` and `vw`.  Use the chrome developer tools to test how the site looks on a mobile device, making sure components are wrapping and expanding their width on smaller viewports.  Also keep in mind how wide you'll allow your content to be- typically, you won't want your component blocks to stretch the entire width.

**Comment by johnhaup** [comment]
We used this in code school as a good intro to the basics: https://flexboxfroggy.com/

**Comment by aaranda82** [comment]
Check
