### ISSUE TITLE
Netlify deployment integration

### ISSUE THREAD

**Issue by johnhaup** [aaranda82/US-Tool#3]
Netlify is a tool that you can connect to your repo that will detect updates to your master branch (or whatever branch you specify- just keep it to master) and build and deploys your new site when changes occur.  It pushes the site live to a randomly-generated url if you don't provide a domain that you own.

Set up integration for this repo and verify the live site works.

**Comment by aaranda82** [comment]
https://elegant-wozniak-b1f84a.netlify.com/
