### ISSUE TITLE
Add prettier

### ISSUE THREAD

**Issue by johnhaup** [aaranda82/US-Tool#4]
Prettier is a code-formatting tool that is helpful for keeping code formatted the same across developers.  Add it to this project with the following basic settings:

  "singleQuote": true,
  "trailingComma": "es5"

**Comment by aaranda82** [comment]
npm installed prettier and updated package.json to include prettier settings

**Comment by johnhaup** [comment]
Make sure you also push the .prettierrc file to the repo so anyone else that works on it has code formatted the same way.

**Comment by aaranda82** [comment]
Done and confirmed that it fixed code
