### ISSUE TITLE
Add linter

### ISSUE THREAD

**Issue by johnhaup** [aaranda82/US-Tool#5]
- [ ] Add a linter file (you can probably a basic config for React apps)

- [ ] Add a script to your package.json that will lint your code (point out errors)

- [ ] Add a script to your package.json that will fix your code, if possible

- [ ] Write incorrectly formatted code and verify the scripts work

**Comment by johnhaup** [comment]
If you redo this repo with typescript, we can close this and discuss typesript configuration

**Comment by aaranda82** [comment]
Done
