### ISSUE TITLE
Add color scheme

### ISSUE THREAD

**Issue by johnhaup** [aaranda82/US-Tool#6]
Choose a color scheme from [https://flatuicolors.com/](https://flatuicolors.com/).  Create a folder called `styles` and a file called `colorScheme.js`.  In that file, export an [enum](https://stackoverflow.com/questions/4709175/what-are-enums-and-why-are-they-useful) where each key of the enum is color name and the value is the hex code for the color.  For example:

```
export enum ColorScheme {
  purple = '#503AF8',
  ...etc
}
```

So now in your styled components (more on this in future issues), instead of typing the hex code for each color, you'll instead import ColorScheme and set the color this way:

`
borderColor: ColorScheme.purple
`

This ensures you have consistent colors across your app.

**Comment by aaranda82** [comment]
added ColorScheme.js with colors to be used
