### ISSUE TITLE
Choose a basic layout for the site

### ISSUE THREAD

**Issue by johnhaup** [aaranda82/US-Tool#7]
**Do this after adding styled components (Issue 8)**

Since the site is pretty basic, choose a basic layout for the site somewhere and let's keep it in the ReadMe for reference.  Take into consideration the site's main goal (likely to gain leads).  We won't be implementing a contact form quite yet, but remember that's most likely what you'll want people visiting the site to use.  The layout can be a full website image or just basic wires.  We just need a guide for what the end result should be.

Using styled components, add a component for each section of the site with a black border and a description of what the section will be centered in the component.

**Comment by aaranda82** [comment]
got it
